config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'players#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :clubs
  resources :matches
  resource :users
  namespace :admin do
    resources :clubs do
      collection do
        resources :update_players, controller: 'clubs/update_players'
      end
    end
    resources :tournaments do
    end
  end
end

app/models/tournament.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  end_date   :integer
#  name       :string           not null
#  start_date :integer
#
class Tournament < ApplicationRecord
  has_many :matches
end

app/controllers/admin/tournaments_controller.rb
class Admin::TournamentsController < ApplicationController
  before_action :authorize!

  def new
  end

  def create
    date = allowed_params[:date]
    official_sheet = allowed_params[:official_sheet]
    allowed_params.delete(:date)
    allowed_params.delete(:official_sheet)
    update = UpdateTournament.new(allowed_params)
    update.data = JSON.generate({date: date, official_sheet: official_sheet})
    update.save!

  end

  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = Tournament.find_by(params[:id])
  end
  private
  def allowed_params
    @allowed_params ||= params.require(:tournament).permit(:file, :date, :official_sheet)
  end

  def authorize!
    authorize Tournament
  end
end

app/views/admin/tournaments/index.html.slim
.container.mx-auto
  .grid.grid-cols-1
    - @tournaments.each do |tournament|
      = link_to tournament.name, admin_tournament_path(tournament)

app/views/admin/tournaments/new.html.slim
= form_with model: Tournament.new, url:admin_tournaments_path  do |f|
  = f.file_field :file
  = f.text_field :date
  = f.check_box :official_sheet
  = f.submit

app/views/admin/tournaments/show.html.slim
- @tournament.matches.each do |match|
  = match.black.name