config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'players#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :clubs
  resources :matches
  resource :users
  namespace :admin do
    resources :clubs do
      collection do
        resources :update_players, controller: 'clubs/update_players'
      end
    end
    resources :tournaments do
    end
  end
end

app/models/player.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: players
#
#  id           :integer          not null, primary key
#  birthyear    :integer
#  display_name :string
#  is_male      :integer          default(1), not null
#  name         :string           not null
#  rating       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  club_id      :integer
#
# Indexes
#
#  index_players_on_club_id             (club_id)
#  index_players_on_name_and_birthyear  (name,birthyear) UNIQUE
#
# Foreign Keys
#
#  club_id  (club_id => clubs.id)
#
class Player < ApplicationRecord
  belongs_to :club, optional: true
  has_many :matches, lambda { |player|
    unscope(:where).where(white: player).or(where(black: player))
  }

  def find_for_club(club_id)
    Player.where(club_id: club_id).all
  end

  def active?
    !matches.empty? && (matches.maximum(:date) >= (Date.today - 365 * 3))
  end

  def screen_name
    return display_name if display_name
    return name.split.map(&:capitalize).join(' ')
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :authorize!
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  def index
    @men = Player.where(is_male: 1).order(rating: :desc).all.filter(&:active?)
    @women = Player.where(is_male: 0).order(rating: :desc).all.filter(&:active?)
  end
end

app/views/players/index.html.slim
h1.container.mx-auto.title
  | Vietnam Go Ratings

.container.mx-auto
  .grid.grid-cols-1.md:grid-cols-2
    table.fixed-size.mx-auto
      thead
        tr
          td Nam
      tbody
        - @men.each_with_index do |player, index|
          tr
            td = index + 1
            td = link_to player.screen_name, matches_path(id: player.id)
            td = player.rating ? player.rating : "-"
    table.fixed-size.mx-auto
      thead
        tr
          td Nu
      tbody
        - @women.each_with_index do |player, index|
          tr
            td = index + 1
            td = link_to player.screen_name, matches_path(id: player.id)
            td = (player.rating != nil) ? player.rating: "-"